import test from "node:test";
import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { createDb, runMigrations, authInstanceState, executorAvailability, activityLog, projects } from "@task-weaver/db";
import { createAuthenticationService } from "./authentication";
import { createIdentityManagementService } from "./identity-management";
import { createResourceServices } from "./resource-services";
import { availableDaemonCapabilities, matchAvailableExecutor } from "./executor-availability";
import { authorizedRealtimeEvent } from "./realtime-authorization";
import { resourceAuthority } from "./resource-authorization";
import { NotFoundError, ConflictError, type ExecutorObservation } from "@task-weaver/contracts";

const databaseUrl=process.env.TW_AUTH_E2E_DATABASE_URL;
test("executor availability is durable, ordered, isolated, authorized and budget safe", {skip:!databaseUrl,timeout:120000},async t=>{
  const url=new URL(databaseUrl!);assert.equal(url.hostname,"127.0.0.1");assert.equal(url.pathname,"/tw_auth_e2e");
  await runMigrations(databaseUrl!);const db=createDb(databaseUrl!);t.after(()=>db.$client.end());
  await db.update(authInstanceState).set({initializedByUserId:null,initializedAt:null});
  const config={secret:randomBytes(32).toString("hex"),bootstrapSecret:randomBytes(32).toString("hex"),baseURL:"http://127.0.0.1:3001",trustedOrigins:["http://127.0.0.1:3000"]};
  const auth=createAuthenticationService(db,config),identity=createIdentityManagementService(db,auth);
  const challenge=auth.csrfChallenge();const headers=new Headers({origin:config.trustedOrigins[0]!,"x-csrf-token":challenge.csrfToken,cookie:challenge.headers.getSetCookie().map(c=>c.split(";")[0]).join("; ")});
  const email=`${randomUUID()}@example.test`,password=randomBytes(24).toString("hex");
  await auth.bootstrap(headers,{email,displayName:"Quota fixture",password,bootstrapSecret:config.bootstrapSecret},"fixture");
  const login=await auth.login(headers,{email,password},"fixture");headers.set("cookie",[headers.get("cookie"),...login.headers.getSetCookie().map(c=>c.split(";")[0])].join("; "));
  const project=await identity.createProject(headers,{name:"Quota fixture"});
  const makeAgent=async()=>{
    const agent=await identity.createAgent(headers,{displayName:"Executor fixture"});
    await identity.setMembership(headers,project.id,agent.id,{role:"maintainer",explicitPermissions:[]});
    const key=await identity.issueKey(headers,agent.id,{name:"Executor fixture",expiresAt:null,grants:[{scope:"project",projectId:project.id,permissions:["resource.read","resource.write","execution.run","audit.read"]}]});
    const context=await auth.resolve(new Headers({authorization:`Bearer ${key.rawKey}`}));return{agent,context,service:createResourceServices(context).daemonService};
  };
  const a=await makeAgent(),b=await makeAgent();
  const register=async(owner:typeof a)=>{const id=randomUUID();await owner.service.registerDaemon(db,{id,name:"Quota fixture",role:"executor",capabilities:["codex","executor:codex","claude","executor:claude"],host:"fixture",processStartedAt:new Date().toISOString(),workerCapacity:2},{id:owner.agent.id,type:"agent"});return id};
  const daemon=await register(a),sibling=await register(a),outsider=await register(b);
  let tick=Date.now()-10000;
  const observation=(tool:"codex"|"claude",state:ExecutorObservation["state"],poolId:string|null="shared"):ExecutorObservation=>({eventId:randomUUID(),tool,profileId:"fixture-profile",poolId,toolVersion:"fixture",authenticationMode:"subscription",state,failure:state==="cooling_down"?"quota_exhausted":null,source:state==="available"?"status_query":"structured_error",confidence:"high",observedAt:new Date(tick+=100).toISOString(),staleAt:new Date(Date.now()+60000).toISOString(),resetAt:null,retryAfterSeconds:null,reason:"Sanitized fixture observation",windows:state==="available"?[{bucket:"codex",window:"primary",usedPercent:10,remainingPercent:90,durationMinutes:300,resetAt:null}]:[]});
  await a.service.reportExecutorObservation(db,sibling,observation("codex","unknown"));
  const blocked=observation("codex","cooling_down");await a.service.reportExecutorObservation(db,daemon,blocked);
  assert.equal((await a.service.listExecutorProfiles(db,sibling))[0]!.observation.state,"cooling_down");
  assert.deepEqual(await availableDaemonCapabilities(db,sibling,["codex","executor:codex","claude"]),["claude"]);
  await b.service.reportExecutorObservation(db,outsider,observation("codex","unknown"));
  assert.equal((await b.service.listExecutorProfiles(db,outsider))[0]!.observation.state,"unknown");
  await assert.rejects(b.service.listExecutorProfiles(db,daemon),NotFoundError);
  assert.deepEqual((await b.service.listExecutorDaemons(db)).map(row => row.id), [outsider]);
  assert.ok((await a.service.listExecutorDaemons(db)).some(row => row.id === daemon));
  const stale={...observation("codex","available"),observedAt:new Date(Date.parse(blocked.observedAt)-1).toISOString()};
  await a.service.reportExecutorObservation(db,daemon,stale);
  assert.equal((await a.service.listExecutorProfiles(db,daemon))[0]!.observation.state,"cooling_down");
  await Promise.all([a.service.reportExecutorObservation(db,daemon,blocked),a.service.reportExecutorObservation(db,daemon,blocked)]);
  assert.equal((await db.select().from(activityLog).where(eq(activityLog.entityId,daemon))).length,2); // registration and one transition
  await a.service.reportExecutorObservation(db,daemon,{...observation("codex","unknown"),source:"unsupported"});
  assert.equal((await a.service.listExecutorProfiles(db,daemon))[0]!.observation.state,"cooling_down");
  const reconnected=createDb(databaseUrl!);try { assert.equal((await reconnected.select().from(executorAvailability).where(eq(executorAvailability.daemonId,daemon)))[0]!.observation.state,"cooling_down") }finally{await reconnected.$client.end()}
  await a.service.reportExecutorObservation(db,daemon,observation("claude","available",null));
  assert.equal((await matchAvailableExecutor(db,daemon,["codex","claude"],[],project.id)).eligible,false);
  await db.update(projects).set({executorFallbackPolicy:{allowedTools:["claude"],authenticationMode:"subscription",allowPaidApi:false}}).where(eq(projects.id,project.id));
  assert.equal((await matchAvailableExecutor(db,daemon,["codex","claude"],[],project.id)).executorTool,"claude");
  assert.equal((await matchAvailableExecutor(db,daemon,["codex","claude"],[],project.id,{requestedModel:"fixed-model"})).eligible,false);
  await a.service.reportExecutorObservation(db,daemon,{...observation("claude","available",null),authenticationMode:"api_key"});
  assert.equal((await matchAvailableExecutor(db,daemon,["codex","claude"],[],project.id)).eligible,false);
  assert.equal((await matchAvailableExecutor(db,daemon,["codex","claude"],["executor:codex"],project.id)).eligible,false);
  const managerContext=await auth.resolve(headers),manager=createResourceServices(managerContext).daemonService;
  const row=(await manager.listExecutorProfiles(db,daemon)).find(p=>p.tool==="codex")!;
  await assert.rejects(manager.requestExecutorResume(db,daemon,"codex",{expectedVersion:row.version-1,reason:"Fixture correction"},{id:login.account.actorId,type:"human"}),ConflictError);
  await manager.requestExecutorRefresh(db,daemon,"codex");
  assert.equal((await manager.listExecutorProfiles(db,daemon)).find(p=>p.tool==="codex")!.observation.state,"cooling_down");
  await manager.requestExecutorResume(db,daemon,"codex",{expectedVersion:row.version,reason:"Fixture correction"},{id:login.account.actorId,type:"human"});
  assert.equal((await manager.listExecutorProfiles(db,daemon)).find(p=>p.tool==="codex")!.observation.state,"unknown");
  const event={type:"executor_availability_changed" as const,daemonId:daemon,kind:"all_blocked" as const};
  assert.equal(await authorizedRealtimeEvent(db,await resourceAuthority(db,b.context),event),null);
  assert.equal((await authorizedRealtimeEvent(db,await resourceAuthority(db,managerContext),event))?.daemonId,daemon);
  await identity.disableAgent(headers,a.agent.id);
  await assert.rejects(a.service.listExecutorProfiles(db,daemon));
});
