/** Exact authorized resource/retrieval routes; execution and unconverted surfaces remain closed. */
const ordinaryRoutes: Array<[string, RegExp]> = [
  ["POST", new RegExp("^/api/v1/daemons/[0-9a-fA-F-]{36}/delegations(?:/[0-9a-fA-F-]{36}/renew)?/?$")],
  ["DELETE", new RegExp("^/api/v1/daemons/[0-9a-fA-F-]{36}/delegations/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/daemons/register/?$")],
  ["POST", new RegExp("^/api/v1/daemons/[0-9a-fA-F-]{36}/(?:heartbeat|status|control|apply-task|apply-requirement|apply-review|apply-merge|progress|reconcile)/?$")],
  ["GET", new RegExp("^/api/v1/observability/(?:overview|metrics|history|logs)/?$")],
  ["GET", new RegExp("^/api/v1/(?:projects/[0-9a-fA-F-]{36}/schedules|schedules/[0-9a-fA-F-]{36}(?:/runs)?)/?$")],
  ["POST", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/schedules/?$")],
  ["PATCH", new RegExp("^/api/v1/schedules/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/schedules/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/activity(?:/export)?/?$")],
  ["GET", new RegExp("^/api/v1/ti/(?:configs|policy|runs(?:/[0-9a-fA-F-]{36})?)/?$")],
  ["POST", new RegExp("^/api/v1/ti/(?:configs(?:/default)?|resolve-model)/?$")],
  ["PUT", new RegExp("^/api/v1/ti/policy/?$")],
  ["GET", new RegExp("^/api/v1/agent-usage/(?:runs(?:/[0-9a-fA-F-]{36})?|summary)/?$")],
  ["GET", new RegExp("^/api/v1/(?:projects/[0-9a-fA-F-]{36}/review-policy|requirements/[0-9a-fA-F-]{36}/(?:review-policy|review-runs)|review-runs/[0-9a-fA-F-]{36})/?$")],
  ["PUT", new RegExp("^/api/v1/(?:projects|requirements)/[0-9a-fA-F-]{36}/review-policy/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/review-runs/?$")],
  ["PUT", new RegExp("^/api/v1/review-runs/[0-9a-fA-F-]{36}/(?:checks|findings)/?$")],
  ["POST", new RegExp("^/api/v1/review-runs/[0-9a-fA-F-]{36}/(?:decisions|evaluate)/?$")],
  ["POST", new RegExp("^/api/v1/repositories/?$")],
  ["PATCH", new RegExp("^/api/v1/repositories/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/repositories/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/(?:requirements|tasks)/[0-9a-fA-F-]{36}/repositories/?$")],
  ["DELETE", new RegExp("^/api/v1/(?:requirements|tasks)/[0-9a-fA-F-]{36}/repositories/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/repositories(?:/[0-9a-fA-F-]{36}(?:/readiness)?)?/?$")],
  ["GET", new RegExp("^/api/v1/(?:requirements|tasks)/[0-9a-fA-F-]{36}/repositories/?$")],
  ["GET", new RegExp("^/api/v1/mcp/(?:servers(?:/[0-9a-fA-F-]{36})?|tools/(?:search|[0-9a-fA-F-]{36}))/?$")],
  ["POST", new RegExp("^/api/v1/mcp/(?:servers|servers/[0-9a-fA-F-]{36}/(?:sync|heartbeat|upload-tools|poll)|tools/[0-9a-fA-F-]{36}/call|requests/[0-9a-fA-F-]{36}/result)/?$")],
  ["PATCH", new RegExp("^/api/v1/mcp/servers/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/mcp/servers/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/context/packages(?:/[0-9a-fA-F-]{36}(?:/(?:files|download|health|read))?)?/?$")],
  ["POST", new RegExp("^/api/v1/context/(?:packages/register|packages/[0-9a-fA-F-]{36}/reindex|import(?:/batch)?)/?$")],
  ["PATCH", new RegExp("^/api/v1/context/packages/[0-9a-fA-F-]{36}(?:/versions/[^/]+)?/?$")],
  ["GET", new RegExp("^/api/v1/embeddings/(?:profiles(?:/[0-9a-fA-F-]{36}(?:/(?:preview|usage|generations))?)?|jobs/[0-9a-fA-F-]{36}(?:/items)?)/?$")],
  ["POST", new RegExp("^/api/v1/embeddings/(?:profiles|profiles/[0-9a-fA-F-]{36}/(?:test|enable|disable|rebuild|cleanup)|jobs/[0-9a-fA-F-]{36}/(?:cancel|resume|retry-failed)|generations/[0-9a-fA-F-]{36}/activate)/?$")],
  ["PATCH", new RegExp("^/api/v1/embeddings/profiles/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/search/(?:documents(?:/fulltext)?|tasks|requirements|repositories|all)/?$")],
  ["POST", new RegExp("^/api/v1/search/resolve-titles/?$")],
  ["GET", new RegExp("^/api/v1/context/(?:search|list|bootstrap)/?$")],
  ["GET", new RegExp("^/api/v1/context/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/memories/search/?$")],
  ["GET", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/(?:stats|health|knowledge-graph|board|gantt)/?$")],
  ["GET", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/(?:burndown|task-dependency-graph)/?$")],
  ["GET", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/requirements/heatmap/?$")],
  ["GET", new RegExp("^/api/v1/(?:tasks|documents)/[0-9a-fA-F-]{36}/recommendations/?$")],

  ["GET", new RegExp("^/api/v1/projects/?$")],
  ["POST", new RegExp("^/api/v1/projects/?$")],
  ["GET", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/requirements/?$")],
  ["POST", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/requirements/?$")],
  ["POST", new RegExp("^/api/v1/requirements/batch/?$")],
  ["GET", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/claim/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/release/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/heartbeat/?$")],
  ["GET", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/claim/?$")],
  ["GET", new RegExp("^/api/v1/requirement-claims/?$")],
  ["GET", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/dependencies/?$")],
  ["GET", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/slices/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/slices/?$")],
  ["PATCH", new RegExp("^/api/v1/execution-slices/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/execution-slices/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/dependencies/?$")],
  ["DELETE", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/dependencies/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/document-links/?$")],
  ["DELETE", new RegExp("^/api/v1/requirements/[0-9a-fA-F-]{36}/document-links/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/tasks/?$")],
  ["POST", new RegExp("^/api/v1/projects/[0-9a-fA-F-]{36}/tasks/?$")],
  ["GET", new RegExp("^/api/v1/personal/tasks/?$")],
  ["POST", new RegExp("^/api/v1/personal/tasks/?$")],
  ["POST", new RegExp("^/api/v1/tasks/batch/?$")],
  ["PATCH", new RegExp("^/api/v1/tasks/batch/?$")],
  ["GET", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/status/?$")],
  ["DELETE", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/comments/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/notes/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/dependencies/?$")],
  ["DELETE", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/dependencies/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/claim/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/release/?$")],
  ["POST", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/heartbeat/?$")],
  ["GET", new RegExp("^/api/v1/tasks/[0-9a-fA-F-]{36}/claim/?$")],
  ["GET", new RegExp("^/api/v1/claims/?$")],
  ["POST", new RegExp("^/api/v1/claims/batch/?$")],
  ["GET", new RegExp("^/api/v1/documents/?$")],
  ["POST", new RegExp("^/api/v1/documents/?$")],
  ["GET", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/versions/?$")],
  ["GET", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/versions/compare/?$")],
  ["GET", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/versions/[0-9]+/?$")],
  ["POST", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/revert/?$")],
  ["GET", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/backlinks/?$")],
  ["POST", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/links/?$")],
  ["POST", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/task-links/?$")],
  ["DELETE", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/links/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/documents/[0-9a-fA-F-]{36}/task-links/[0-9a-fA-F-]{36}/?$")],
  ["POST", new RegExp("^/api/v1/memories/?$")],
  ["GET", new RegExp("^/api/v1/memories/?$")],
  ["GET", new RegExp("^/api/v1/memories/entity/(?:project|requirement|task|document)/[0-9a-fA-F-]{36}/?$")],
  ["PATCH", new RegExp("^/api/v1/memories/[0-9a-fA-F-]{36}/?$")],
  ["DELETE", new RegExp("^/api/v1/memories/[0-9a-fA-F-]{36}/?$")],
  ["GET", new RegExp("^/api/v1/memories/[0-9a-fA-F-]{36}/?$")],
];
export function isOrdinaryResourceRoute(method: string, path: string) {
  if (method === "GET" && path === "/api/v1/daemons/events") return true;
  if (["GET", "POST"].includes(method) && /^\/api\/v1\/webhooks\/?$/.test(path)) return true;
  if (["GET", "PATCH", "DELETE"].includes(method) && /^\/api\/v1\/webhooks\/[0-9a-fA-F-]{36}$/.test(path)) return true;
  if (method === "GET" && /^\/api\/v1\/webhooks\/[0-9a-fA-F-]{36}\/deliveries$/.test(path)) return true;
  if (method === "POST" && /^\/api\/v1\/webhooks\/[0-9a-fA-F-]{36}\/(?:test|deliveries\/[0-9a-fA-F-]{36}\/retry)$/.test(path)) return true;
  if (method === "POST" && /^\/api\/v1\/ti\/runs(?:\/acquire|\/[0-9a-fA-F-]{36}\/(?:complete|heartbeat|progress|retry|delegations(?:\/[0-9a-fA-F-]{36}\/renew)?))?\/?$/.test(path)) return true;
  if (method === "POST" && /^\/api\/v1\/schedules\/[0-9a-fA-F-]{36}\/run-now$/.test(path)) return true;
  if (method === "POST" && /^\/api\/v1\/assistant\/actions\/[0-9a-fA-F-]{36}\/execute$/.test(path)) return true;
  return ordinaryRoutes.some(([verb, pattern]) => verb === method && pattern.test(path));
}
